[server]
headless = true
address = "0.0.0.0"
port = 8501

[theme]
# Primary colors
primaryColor = "#3b82f6"
backgroundColor = "#1e3a5f"
secondaryBackgroundColor = "#2563eb"
textColor = "#ffffff"

# Font
font = "sans serif"

# Base theme (can be "light" or "dark")
base = "dark"
